server:
  port: 0
spring:
  application:
    name: quest
  r2dbc:
    url: r2dbc:postgresql://localhost/quest_db
    username: user
    password: password
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost/quest_db
    user: user
    password: password
    change-log: db/changelog/master-changelog.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
#  instance:
#    instance-id: ${spring.application.name}:${random.uuid}

kafka:
  server: localhost:9092
  group:
    id: server.broadcast
  producer:
    id: producerServer
  topic: server.damage

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    operations-sorter: method

client:
  gateway:
    url: ${gatewayUrl:http://localhost:8080}

job:
  #    every day at 23:00:00 (UTC)
  cron: 0 0 23 * * *
